# Generated by Django 5.1.1 on 2025-02-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='QQ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
